version: "3"
services:
  bot:
    build: .
    container_name: bot
    user: "node"
    volumes:
      - ./actions:/opt/bot/actions
      - ./app.js:/opt/bot/app.js
      - ./cmd-bot.js:/opt/bot/cmd-bot.js
      - ./config.json:/opt/bot/config.json
      - ./info.json:/opt/bot/info.json
    working_dir: /opt/bot
    command: node app.js
    restart: always
